export const KEYS = {
  AVAILABLE_USERS: "AVAILABLE_USERS",
  CURRENT_USER: "CURRENT_USER",
  APPLICATIONS: "APPLICATIONS",
};

export const STATUS = {
  PENDING: "PENDING",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
};

export const ROLES = {
  STUDENT: "STUDENT",
  ADMIN: "ADMIN",
};
